### PR TITLE
Configurable MQTT package size in Controller.ino

### PR DESCRIPTION
**Pull request by ToniA**
A problem was found with Domoticz MQTT testing, when sending heatpumpir commands via Domoticz MQTT api. MQTT_MAX_PACKET_SIZE is already a setting in platformio.ini

### CODE REVIEW

**Comment by TD-er** [comment]
It is a setting in platform.ini, since it must be known at compile time, not run time.
Or else I must change some code in the PubSubClient library.

What size does it have to be?
Then I can add it to the build containing this plugin, in this PR: https://github.com/letscontrolit/ESPEasy/pull/2543

**Comment by TD-er** [comment]
I cherry picked your commit to the main repository and added some more changes to your commit too.
They are added to the pull request.

Is the max of 1024 long enough? Or should I change that one also in the builds containing this plugin?

**Comment by ToniA** [comment]
I think 512 is plenty enough, but 384 was a bit too small value with Domoticz MQTT.

**Comment by TD-er** [comment]
It was for sure a bug, since they should be related to each other.
What is the use of allocating more space for a message, but not using it.

**Pull request closed without merging**
