### PR TITLE
Compile error

### PR DESCRIPTION
**Pull request by s0170071**
stray "\"

### CODE REVIEW

**Comment by s0170071** [comment]
stray "\\" ... hmm. Came across this one before.

**Comment by TD-er** [comment]
Are you sure about the merge?
I did not have any compile error here before commit/push

A quick search shows 83 occurrences of these in the source ;)

**Comment by s0170071** [comment]
I got the error with Arduino IDE on Linux it says stray \

**Comment by s0170071** [comment]
```
ompiling sketch...
"/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/tmp/arduino_build_943833/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10805 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_WEMOS_D1MINI"  -DESP8266 "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/variants/d1_mini" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/DNSServer/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/Wire" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/SPI" "-I/home/john/Arduino/scetchbooks/libraries/pubsubclient/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/Servo/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/SD/src" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266HTTPUpdateServer/src" "-I/home/john/Arduino/scetchbooks/libraries/ArduinoJson" "-I/home/john/Arduino/scetchbooks/libraries/AS_BH1750" "-I/home/john/Arduino/scetchbooks/libraries/LiquidCrystal_I2C" "-I/home/john/Arduino/scetchbooks/libraries/IRremoteESP8266" "-I/home/john/Arduino/scetchbooks/libraries/esp8266-oled-ssd1306" "-I/home/john/Arduino/scetchbooks/libraries/Adafruit_NeoPixel" "-I/home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/tmp/arduino_build_943833/sketch/ESPEasy.ino.cpp" -o "/tmp/arduino_build_943833/sketch/ESPEasy.ino.cpp.o"
Misc:1415: error: stray '\' in program
   \*********************************************************************************************/
   ^
Misc:1414: error: expected unqualified-id before '/' token
 // replace other system variables like %sysname%, %systime%, %ip%
  ^
In file included from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/../Internals/JsonWriter.hpp:11:0,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/../Internals/JsonPrintable.hpp:13,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/../JsonVariant.hpp:13,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/../JsonBuffer.hpp:14,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/BlockJsonBuffer.hpp:10,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/DynamicJsonBuffer.hpp:10,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson.hpp:10,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson.h:8,
                 from /home/john/Arduino/scetchbooks/libraries/ArduinoJson/ArduinoJson.h:8,
                 from /home/john/Arduino/scetchbooks/ESPEasy/_C002.ino:9:
/home/john/Arduino/scetchbooks/libraries/ArduinoJson/include/ArduinoJson/Internals/../Internals/../Polyfills/math.hpp:36:28: error: expected declaration before end of line
 #pragma GCC diagnostic push
                            ^
Multiple libraries were found for "Servo.h"
 Used: /home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/Servo
 Not used: /home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/libraries/Servo
Multiple libraries were found for "SD.h"
 Used: /home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/portable/packages/esp8266/hardware/esp8266/2.3.0/libraries/SD
 Not used: /home/john/ArduinoPortable/arduino-1.8.5_ESP2.3.0/libraries/SD
```

**Comment by s0170071** [comment]
got it. The solution lies in the extra "//". All other comments which have a /***\ do not have a "//" in the line that follows. 

```
/********************************************************************************************\
// replace other system variables like %sysname%, %systime%, %ip%
  \*********************************************************************************************/
Remaining question is: why don't you get the error ?
```

**Comment by s0170071** [comment]
related: http://www.cplusplus.com/forum/beginner/38985/
"\ \" is a c++ line break.

**Comment by TD-er** [comment]
Indeed.
But rather strange, the PlatformIO compiler doesn't complain about it.

**Comment by s0170071** [comment]
Is it a different compiler? I thought it comes with the Espressif SDK.

**Comment by TD-er** [comment]
It is on Windows. Maybe that also makes a difference?
But the Travis CI also did not complain, and that's Linux I guess.

**Pull request closed without merging**
